moved bin/mymkr to mymkr/mymkr, basic execution works

diff --git a/mymkr/mymkr b/mymkr/mymkr
--- a/mymkr/mymkr
+++ b/mymkr/mymkr
@@ -22,16 +22,23 @@ color_cyan='\E[36m'
 color_white='\E[37m'
 color_off='\E[0m'
 
-notice () {
-	echo -e "${color_green}[MYMKR NOTICE]${color_off} ${@}"
+msg_info () {
+	echo -e "${color_green}[MYMKR:INFO]${color_off} ${@}"
+}
+
+msg_warning () {
+	echo -e "${color_yellow}[MYMKR:WARNING]${color_off} ${@}"
+}
+
+msg_error () {
+	echo -e "${color_red}[MYMKR:ERROR]${color_off} ${@}"
 }
 
 die () {
-	echo -e "${color_red}[MYMKR ERROR]${color_off} ${@}"
+	msg_error ${@}
 	exit 1
 }
 
-die("TEST")
 
 ########################################################################
 # build/install MYMKR directory
@@ -41,22 +48,48 @@ test ! -d $MYMKR_PREFIX && mkdir $MYMKR_PREFIX
 test ! -d $MYMKR_PREFIX/src && mkdir $MYMKR_PREFIX/src
 test ! -d $MYMKR_PREFIX/bin && mkdir $MYMKR_PREFIX/bin
 E="$MYMKR_PREFIX/mymkr/env"
-touch "$E" || die "failed to create MYMKR environment"
-echo "MYMKR_PREFIX=$MYMKR_PREFIX" > $E
-echo "export MYMKR_PREFIX=\$MYMKR_PREFIX" >> $E
-echo "export PKG_CONFIG_PATH=\$MYMKR_PREFIX/lib/pkgconfig" >> $E
-echo "export LD_LIBRARY_PATH=\$MYMKR_PREFIX/lib" >> $E
-echo "export PATH=\$MYMKR_PREFIX/bin:\$PATH" >> $E
-echo "export MANPATH=\$MYMKR_PREFIX/share/man:/usr/share/man" >> $E
-echo "export XDG_DATA_DIRS=\$MYMKR_PREFIX/share:\$XDG_DATA_DIRS" >> $E
-echo "export PYTHONPATH=\${PYTHONPATH}:\$MYMKR_PREFIX/lib/python2.7/site-packages" >> $E
-grep "$MYMKR_PREFIX/env" ~/.bashrc || echo "source $MYMKR_PREFIX/env" >> ~/.bashrc
+if [ ! -f "$E" ]
+then
+	msg_info "MYMKR environment definition ($E) does no exist, creating"
+	touch "$E" || die "failed to create MYMKR environment"
+	echo "MYMKR_PREFIX=$MYMKR_PREFIX" > $E
+	echo "export MYMKR_PREFIX=\$MYMKR_PREFIX" >> $E
+	echo "export PKG_CONFIG_PATH=\$MYMKR_PREFIX/lib/pkgconfig" >> $E
+	echo "export LD_LIBRARY_PATH=\$MYMKR_PREFIX/lib" >> $E
+	echo "export PATH=\$MYMKR_PREFIX/bin:\$PATH" >> $E
+	echo "export MANPATH=\$MYMKR_PREFIX/share/man:/usr/share/man" >> $E
+	echo "export XDG_DATA_DIRS=\$MYMKR_PREFIX/share:\$XDG_DATA_DIRS" >> $E
+	echo "export PYTHONPATH=\${PYTHONPATH}:\$MYMKR_PREFIX/lib/python2.7/site-packages" >> $E
+	grep "$E" ~/.bashrc || echo "source $E" >> ~/.bashrc
+fi
 source $E
 
 
 ########################################################################
+# $1: a directory of MYMKR package definitions
+get_pkgs ()
+{
+	test -z "$1" && die "get_pkgs: invalid paramaters"
+	for x in $(find $1 -mindepth 1)
+	do
+		basename $x | sed -e 's/.sh//' 
+	done
+}
 
-D="$MYMKR_PREFIX/mymkr/"
+D="$MYMKR_PREFIX/mymkr"
+PKGS=$(get_pkgs "$D/pkgs/")
+
+if [ -z "$1" ]
+then
+	echo "USAGE: $0 <package>"
+	echo -e "<package> is one of:"
+	echo -e "\tclean   (cleans build related files)"
+	for x in $PKGS; do echo -e "\t$x"; done
+	exit 1
+fi
+
+for x in $(find $D/fetch  -mindepth 1 | egrep "\.sh$"); do source $x; done
+for x in $(find $D/common -mindepth 1 | egrep "\.sh$"); do source $x; done
 
 # if package has a directory, install all pkgs inside it first
 if [ -d "$D/pkgs/$1" ]
@@ -64,15 +97,15 @@ then
 	#die (':TODO: implement package defined as directory')
 	for x in $(ls $D/pkgs/$1)
 	do
-		notice(":TODO: mk $x")
+		msg_info ":TODO: mk $x"
 	done
 fi
 
 # if package has an install script
 if [ -f "$D/pkgs/$1.sh" ]
 then
-	#source "$D/pkgs/$1.sh"
-	notice(":TODO: source $D/pkgs/$1.sh")
+	msg_info "source $D/pkgs/$1.sh"
+	source "$D/pkgs/$1.sh"
 fi
 
 # if package's install script is inside a directory
@@ -83,15 +116,5 @@ fi
 #then
 #fi
 
-PKGS=$(find $D/pkgs | sed -e 's/.sh//' | sed -e "s/$D//" | uniq)
-case $1 in
-	*)
-		echo "USAGE: $0 <package>"
-		echo -e "<package> is one of:"
-		echo -e "\tclean   (cleans build related files)"
-		for x in $PKGS; do echo -e "\t$x"; done
-		exit 1
-		;;
-esac
 
 exit 0
